// lit-element/src/components/Search.ts
import { LitElement, html, customElement } from 'lit-element';


@customElement('frida-search')
export class Search extends LitElement {
  render() {
    return html`
        <style>
            
            button {
                background: whitesmoke;
                padding: 0.5rem;
                border: 0;
            }
            
        </style>
        <input/>
        <button @click="${this.onClick.bind(this)}">Search</button>
    `;
  }

  private onClick() {
    this.dispatchEvent(new CustomEvent('search', {
      detail: {
        search: (<HTMLInputElement>this.shadowRoot?.querySelector('input')).value
      }
    }));
  }

  


}

// react/src/components/Search/Search.jsx
import React from 'react';
import './Search.css';

export default class Form extends React.Component {
 

  render() {
    return <div><input/> <button onclick={this.onClick.bind(this)}>Search</button></div>;
  }

  onClick() {
    this.dispatchEvent(new CustomEvent('search', {
      detail: {
        search: (this.querySelector('input')).value
      }
    }));
  }

}
