// lit-element/src/components/Post.ts
import { LitElement, html, css, customElement, property } from "lit-element";

type IPost = {
  heading: string;
  sentence: string;
};

@customElement("frida-post")
export class Post extends LitElement {
  public static styles = css`
    :host {
       display: block;
    }
  `;

  @property({ type: "object" })
  public post: IPost|null = null;

  render() {
    return html`
      <h3>${this.post?.heading}</h3><p>${this.post?.sentence}</p>
    `;
  }
}

// react/src/components/Post/Post.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './Post.css';

  
export default class Post extends React.Component {

    static propTypes = {
        post: PropTypes.object
    };

  render() {
    return <div id="post"><h3>{this.props.post?.heading}</h3><p>{this.props.post?.sentence}</p></div>;
  }
}
